version: "3.9"

services:
  postgres:
    hostname: postgres
    image: postgres
    volumes:
      - pg-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  init-db:
    build:
      context: .
      dockerfile: init/Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "postgres"

  webapp:
    build: .
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      DB_HOST: "postgres"
      APP_MODE: "release"
    entrypoint: "/usr/local/bin/app"
    depends_on:
      - postgres

volumes:
  pg-database: