###
POST http://127.0.0.1:9000/users/add
Content-Type: application/json

{
  "username": "ivan 452"
}


###
POST http://localhost:9000/chats/add
Content-Type: application/json

{
  "name": "Chat 1",
  "users": [
    1
  ]
}