###
POST http://127.0.0.1:9000/users/add
Content-Type: application/json

{
  "username": "ivan 8"
}


###
POST http://127.0.0.1:9000/chats/add
Content-Type: application/json

{
  "name": "Chat 12124",
  "users": [
    9
  ]
}

###
POST http://127.0.0.1:9000/messages/add
Content-Type: application/json

{
  "chat": 6,
  "author":9,
  "text": "Text"
}

###
POST http://127.0.0.1:9000/chats/get
Content-Type: application/json

{
  "user": 9
}

###
POST http://127.0.0.1:9000/messages/get
Content-Type: application/json

{
  "chat": 6
}