###
POST http://127.0.0.1:9000/users/add
Content-Type: application/json

{
  "username": "ivan 6"
}


###
POST http://127.0.0.1:9000/chats/add
Content-Type: application/json

{
  "name": "Chat 1212",
  "users": [
    1, 4
  ]
}

###
POST http://127.0.0.1:9000/messages/add
Content-Type: application/json

{
  "chat": 4,
  "author": 4,
  "text": "Text"
}

###
POST http://127.0.0.1:9000/chats/get
Content-Type: application/json

{
  "user": 4
}

###
POST http://127.0.0.1:9000/messages/get
Content-Type: application/json

{
  "chat": 4
}