basePath: /
definitions:
  v1.chatId:
    properties:
      chatId:
        type: integer
    type: object
  v1.errorJSON:
    properties:
      message:
        type: string
    type: object
  v1.userId:
    properties:
      userId:
        type: integer
    type: object
host: 127.0.0.1:9000
info:
  contact:
    email: levayu22@gmail.com
    name: Lev Yuvensky
  title: Avito-tech backend trainee task 2020
  version: "1.0"
paths:
  /chats/add:
    post:
      consumes:
      - application/json
      description: Create a new user with name and users.
      operationId: createChat
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.chatId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorJSON'
      summary: Create new chat
      tags:
      - chat
  /users/add:
    post:
      consumes:
      - application/json
      description: Create a new user with username.
      operationId: createUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.userId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorJSON'
      summary: Create new user
      tags:
      - user
swagger: "2.0"
