basePath: /
definitions:
  apperror.ErrorJSON:
    properties:
      message:
        type: string
    type: object
  models.ChatId:
    properties:
      chatId:
        type: integer
    type: object
  models.CreateChatDTO:
    properties:
      name:
        type: string
      users:
        items:
          type: integer
        type: array
    required:
    - name
    - users
    type: object
  models.CreateMessageDTO:
    properties:
      author:
        type: integer
      chat:
        type: integer
      text:
        type: string
    required:
    - author
    - chat
    - text
    type: object
  models.CreateUserDTO:
    properties:
      username:
        type: string
    required:
    - username
    type: object
  models.GetChatMessagesDRORequest:
    properties:
      chat:
        type: integer
    required:
    - chat
    type: object
  models.GetUserChatsDTOResponse:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      users:
        items:
          type: integer
        type: array
    type: object
  models.GetUserChatsDTORequest:
    properties:
      user:
        type: integer
    required:
    - user
    type: object
  models.Message:
    properties:
      author:
        type: integer
      chat:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      text:
        type: string
    type: object
  models.MessageId:
    properties:
      messageId:
        type: integer
    type: object
  models.UserId:
    properties:
      userId:
        type: integer
    type: object
host: 127.0.0.1:9000
info:
  contact:
    email: levayu22@gmail.com
    name: Lev Yuvensky
  title: Avito.tech's task for backend trainee (2020 year)
  version: "1.0"
paths:
  /chats/add:
    post:
      consumes:
      - application/json
      description: Create a new chat with name and list of users.
      operationId: createChat
      parameters:
      - description: Parameters for creating a chat.
        in: body
        name: createChatObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateChatDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ChatId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Create new chat
      tags:
      - chat
  /chats/get:
    post:
      consumes:
      - application/json
      description: Get a list of user chats by user ID.
      operationId: getUserChats
      parameters:
      - description: Parameters for getting user chats.
        in: body
        name: getUserChatsObject
        required: true
        schema:
          $ref: '#/definitions/models.GetUserChatsDTORequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.GetUserChatsDTOResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get a list of user chats
      tags:
      - chat
  /messages/add:
    post:
      consumes:
      - application/json
      description: Create a new message with chat's id, author's id and text.
      operationId: createMessage
      parameters:
      - description: Parameters for creating a message.
        in: body
        name: createMessageObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateMessageDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.MessageId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Create new message
      tags:
      - message
  /messages/get:
    post:
      consumes:
      - application/json
      description: Get a list of chat messages by chat ID.
      operationId: GetChatMessages
      parameters:
      - description: Parameters for getting chat messages.
        in: body
        name: getChatsMessagesObject
        required: true
        schema:
          $ref: '#/definitions/models.GetChatMessagesDRORequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Get a list of chat messages
      tags:
      - message
  /users/add:
    post:
      consumes:
      - application/json
      description: Create a new user with username.
      operationId: createUser
      parameters:
      - description: Parameters for creating a user.
        in: body
        name: createUserObject
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.ErrorJSON'
      summary: Create new user
      tags:
      - user
swagger: "2.0"
